// Code generated by hive. DO NOT EDIT.

package rpc

import (
    "google.golang.org/grpc"
	"strconv"
	"github.com/benka-me/laruche/go-pkg/discover"
	"fmt"

)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Sprintf("")
var _ = strconv.FormatInt(int64(0), 10)

type Clients struct {

}

func    InitClients(engine discover.Engine,  options ...grpc.DialOption) Clients {

    return Clients{

    }
}
